In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
df = pd.read_csv('../datasets/tableau.csv')

In [3]:
df

,airport,year,month,carrier,carrier_name,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,late_aircraft_delay,type,name,latitude_deg,longitude_deg,elevation_ft,iso_country,iso_region,municipality,gps_code
0,ABE,2022,7,9E,Endeavor Air Inc.,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",33.0,2.0,0.92,1.00,...,0.0,medium_airport,Lehigh Valley International Airport,40.652100,-75.440804,393.0,US,US-PA,Allentown,KABE
1,ABE,2022,7,G4,Allegiant Air,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",174.0,68.0,12.44,5.98,...,2614.0,medium_airport,Lehigh Valley International Airport,40.652100,-75.440804,393.0,US,US-PA,Allentown,KABE
2,ABE,2022,7,MQ,Envoy Air,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",61.0,7.0,1.34,0.00,...,327.0,medium_airport,Lehigh Valley International Airport,40.652100,-75.440804,393.0,US,US-PA,Allentown,KABE
3,ABE,2022,7,OH,PSA Airlines Inc.,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",84.0,20.0,5.66,1.11,...,360.0,medium_airport,Lehigh Valley International Airport,40.652100,-75.440804,393.0,US,US-PA,Allentown,KABE
4,ABE,2022,7,OO,SkyWest Airlines Inc.,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",76.0,28.0,22.00,6.00,...,0.0,medium_airport,Lehigh Valley International Airport,40.652100,-75.440804,393.0,US,US-PA,Allentown,KABE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327221,YUM,2003,10,OO,SkyWest Airlines Inc.,"Yuma, AZ: Yuma MCAS/Yuma International",94.0,6.0,1.00,1.00,...,61.0,medium_airport,Yuma MCAS/Yuma International Airport,32.656601,-114.606003,213.0,US,US-AZ,Yuma,KNYL
327222,YUM,2003,9,OO,SkyWest Airlines Inc.,"Yuma, AZ: Yuma MCAS/Yuma International",89.0,8.0,5.00,1.00,...,134.0,medium_airport,Yuma MCAS/Yuma International Airport,32.656601,-114.606003,213.0,US,US-AZ,Yuma,KNYL
327223,YUM,2003,8,OO,SkyWest Airlines Inc.,"Yuma, AZ: Yuma MCAS/Yuma International",93.0,4.0,4.00,0.00,...,0.0,medium_airport,Yuma MCAS/Yuma International Airport,32.656601,-114.606003,213.0,US,US-AZ,Yuma,KNYL
327224,YUM,2003,7,OO,SkyWest Airlines Inc.,"Yuma, AZ: Yuma MCAS/Yuma International",92.0,4.0,3.00,0.00,...,0.0,medium_airport,Yuma MCAS/Yuma International Airport,32.656601,-114.606003,213.0,US,US-AZ,Yuma,KNYL
327225,YUM,2003,6,OO,SkyWest Airlines Inc.,"Yuma, AZ: Yuma MCAS/Yuma International",90.0,4.0,0.00,0.00,...,69.0,medium_airport,Yuma MCAS/Yuma International Airport,32.656601,-114.606003,213.0,US,US-AZ,Yuma,KNYL

In [4]:
df_airports = df[['airport', 'airport_name', 'municipality', 'iso_region', 'iso_country', 'elevation_ft','latitude_deg', 'longitude_deg']].drop_duplicates().dropna().reset_index(drop=True)

In [5]:
df_airports.to_csv('airports_cleaned.csv', index=False)

In [6]:
df = df[['airport',
 'year',
 'month',
 'carrier',
 'carrier_name',
 'arr_flights',
 'arr_del15',
 'carrier_ct',
 'weather_ct',
 'nas_ct',
 'security_ct',
 'late_aircraft_ct',
 'arr_cancelled',
 'arr_diverted',
 'arr_delay',
 'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay']]

In [7]:
df_airports

,airport,airport_name,municipality,iso_region,iso_country,elevation_ft,latitude_deg,longitude_deg
0,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",Allentown,US-PA,US,393.0,40.652100,-75.440804
1,ABI,"Abilene, TX: Abilene Regional",Abilene,US-TX,US,1791.0,32.411301,-99.681900
2,ABQ,"Albuquerque, NM: Albuquerque International Sun...",Albuquerque,US-NM,US,5355.0,35.040199,-106.609001
3,ABR,"Aberdeen, SD: Aberdeen Regional",Aberdeen,US-SD,US,1302.0,45.449100,-98.421799
4,ABY,"Albany, GA: Southwest Georgia Regional",Albany,US-GA,US,197.0,31.535500,-84.194504
...,...,...,...,...,...,...,...,...
403,XNA,"Fayetteville, AR: Northwest Arkansas Regional",Fayetteville/Springdale,US-AR,US,1287.0,36.281898,-94.306801
404,YAK,"Yakutat, AK: Yakutat Airport",Yakutat,US-AK,US,33.0,59.503300,-139.660004
405,YKM,"Yakima, WA: Yakima Air Terminal/McAllister Field",Yakima,US-WA,US,1099.0,46.568199,-120.543999
406,YNG,"Youngstown/Warren, OH: Youngstown-Warren Regional",Youngstown/Warren,US-OH,US,1192.0,41.260700,-80.679100
407,YUM,"Yuma, AZ: Yuma MCAS/Yuma International",Yuma,US-AZ,US,213.0,32.656601,-114.606003

In [8]:
conn = sqlite3.connect('../databases/airports_delay.db')
conn.execute("DROP TABLE IF EXISTS airports;")
conn.execute("DROP TABLE IF EXISTS delays;")

In [9]:

with sqlite3.connect('../databases/airports_delay.db') as con:
    df_airports.to_sql('airports', con=con, index=False, dtype={'airport': 'TEXT PRIMARY KEY',
                                                     'airport_name': 'TEXT',
                                                     'municipality': 'TEXT',
                                                     'iso_region': 'TEXT',
                                                     'iso_country': 'TEXT',
                                                     'elevation_ft': 'REAL',
                                                     'latitude_deg':'REAL',
                                                     'latitude_deg': 'REAL'})

In [10]:
pd.read_sql('select * from airports', conn)

,airport,airport_name,municipality,iso_region,iso_country,elevation_ft,latitude_deg,longitude_deg
0,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",Allentown,US-PA,US,393.0,40.652100,-75.440804
1,ABI,"Abilene, TX: Abilene Regional",Abilene,US-TX,US,1791.0,32.411301,-99.681900
2,ABQ,"Albuquerque, NM: Albuquerque International Sun...",Albuquerque,US-NM,US,5355.0,35.040199,-106.609001
3,ABR,"Aberdeen, SD: Aberdeen Regional",Aberdeen,US-SD,US,1302.0,45.449100,-98.421799
4,ABY,"Albany, GA: Southwest Georgia Regional",Albany,US-GA,US,197.0,31.535500,-84.194504
...,...,...,...,...,...,...,...,...
403,XNA,"Fayetteville, AR: Northwest Arkansas Regional",Fayetteville/Springdale,US-AR,US,1287.0,36.281898,-94.306801
404,YAK,"Yakutat, AK: Yakutat Airport",Yakutat,US-AK,US,33.0,59.503300,-139.660004
405,YKM,"Yakima, WA: Yakima Air Terminal/McAllister Field",Yakima,US-WA,US,1099.0,46.568199,-120.543999
406,YNG,"Youngstown/Warren, OH: Youngstown-Warren Regional",Youngstown/Warren,US-OH,US,1192.0,41.260700,-80.679100
407,YUM,"Yuma, AZ: Yuma MCAS/Yuma International",Yuma,US-AZ,US,213.0,32.656601,-114.606003

In [11]:
df

,airport,year,month,carrier,carrier_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,ABE,2022,7,9E,Endeavor Air Inc.,33.0,2.0,0.92,1.00,0.08,0.0,0.00,0.0,0.0,129.0,98.0,23.0,8.0,0.0,0.0
1,ABE,2022,7,G4,Allegiant Air,174.0,68.0,12.44,5.98,11.54,0.0,38.04,1.0,1.0,4858.0,957.0,556.0,731.0,0.0,2614.0
2,ABE,2022,7,MQ,Envoy Air,61.0,7.0,1.34,0.00,1.12,0.0,4.55,1.0,0.0,486.0,84.0,0.0,75.0,0.0,327.0
3,ABE,2022,7,OH,PSA Airlines Inc.,84.0,20.0,5.66,1.11,7.62,0.0,5.61,3.0,0.0,1065.0,268.0,99.0,338.0,0.0,360.0
4,ABE,2022,7,OO,SkyWest Airlines Inc.,76.0,28.0,22.00,6.00,0.00,0.0,0.00,4.0,0.0,2884.0,2018.0,866.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327221,YUM,2003,10,OO,SkyWest Airlines Inc.,94.0,6.0,1.00,1.00,2.00,0.0,2.00,3.0,0.0,236.0,60.0,23.0,92.0,0.0,61.0
327222,YUM,2003,9,OO,SkyWest Airlines Inc.,89.0,8.0,5.00,1.00,0.00,0.0,2.00,2.0,0.0,365.0,213.0,18.0,0.0,0.0,134.0
327223,YUM,2003,8,OO,SkyWest Airlines Inc.,93.0,4.0,4.00,0.00,0.00,0.0,0.00,0.0,0.0,86.0,86.0,0.0,0.0,0.0,0.0
327224,YUM,2003,7,OO,SkyWest Airlines Inc.,92.0,4.0,3.00,0.00,1.00,0.0,0.00,0.0,0.0,119.0,102.0,0.0,17.0,0.0,0.0
327225,YUM,2003,6,OO,SkyWest Airlines Inc.,90.0,4.0,0.00,0.00,0.00,1.0,3.00,0.0,0.0,122.0,0.0,0.0,0.0,53.0,69.0

In [12]:
with sqlite3.connect('../databases/airports_delay.db') as con:
    df.to_sql('delays', con=con, index=False, dtype={'id': 'INTEGER PRIMARY KEY',
                                                     'airport': 'TEXT',
                                                     'year': 'TEXT',
                                                     'month': 'TEXT',
                                                     'carrier': 'TEXT',
                                                     'carrier_name': 'REAL',
                                                     'arr_flights':'REAL',
                                                     'arr_del15': 'REAL',
                                                     'carrier_ct': 'REAL',
                                                     'weather_ct': 'REAL',
                                                     'nas_ct': 'REAL',
                                                     'security_ct': 'REAL',
                                                     'late_aircraft_ct': 'REAL',
                                                     'arr_cancelled': 'REAL',
                                                     'arr_diverted': 'REAL',
                                                     'arr_delay': 'REAL',
                                                     'carrier_delay': 'REAL',
                                                     'weather_delay': 'REAL',
                                                     'nas_delay': 'REAL',
                                                     'security_delay': 'REAL',
                                                     'late_aircraft_delay': 'REAL'
                                                    })

In [13]:
pd.read_sql('select * from delays', conn)

,airport,year,month,carrier,carrier_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,ABE,2022,7,9E,Endeavor Air Inc.,33.0,2.0,0.92,1.00,0.08,0.0,0.00,0.0,0.0,129.0,98.0,23.0,8.0,0.0,0.0
1,ABE,2022,7,G4,Allegiant Air,174.0,68.0,12.44,5.98,11.54,0.0,38.04,1.0,1.0,4858.0,957.0,556.0,731.0,0.0,2614.0
2,ABE,2022,7,MQ,Envoy Air,61.0,7.0,1.34,0.00,1.12,0.0,4.55,1.0,0.0,486.0,84.0,0.0,75.0,0.0,327.0
3,ABE,2022,7,OH,PSA Airlines Inc.,84.0,20.0,5.66,1.11,7.62,0.0,5.61,3.0,0.0,1065.0,268.0,99.0,338.0,0.0,360.0
4,ABE,2022,7,OO,SkyWest Airlines Inc.,76.0,28.0,22.00,6.00,0.00,0.0,0.00,4.0,0.0,2884.0,2018.0,866.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327221,YUM,2003,10,OO,SkyWest Airlines Inc.,94.0,6.0,1.00,1.00,2.00,0.0,2.00,3.0,0.0,236.0,60.0,23.0,92.0,0.0,61.0
327222,YUM,2003,9,OO,SkyWest Airlines Inc.,89.0,8.0,5.00,1.00,0.00,0.0,2.00,2.0,0.0,365.0,213.0,18.0,0.0,0.0,134.0
327223,YUM,2003,8,OO,SkyWest Airlines Inc.,93.0,4.0,4.00,0.00,0.00,0.0,0.00,0.0,0.0,86.0,86.0,0.0,0.0,0.0,0.0
327224,YUM,2003,7,OO,SkyWest Airlines Inc.,92.0,4.0,3.00,0.00,1.00,0.0,0.00,0.0,0.0,119.0,102.0,0.0,17.0,0.0,0.0
327225,YUM,2003,6,OO,SkyWest Airlines Inc.,90.0,4.0,0.00,0.00,0.00,1.0,3.00,0.0,0.0,122.0,0.0,0.0,0.0,53.0,69.0